engines:
  rubocop:
    enabled: true
    #checks:
    # Rubocop/Metrics/ClassLength:
    #   enabled: false
  coffeelint:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
ratings:
  paths:
  - app/**
  - "**.rb"
  - "**.go"
exclude_paths:
- "**/vendor/**/*"
- public/**/*
- tests/**/*
- spec/**/*
- features/step_definitions/web_steps.rb
